trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.csproj'
  configuration: release

steps:
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(configuration)'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: DotNetCoreCLI@2
  displayName: 'Pack packages'
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: '$(solution)'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'