trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Namotion.Reflection.sln'
    arguments: '--configuration Release'
    feedsToUse: 'select'
    versioningScheme: 'off'
